version: 2
updates:
  - package-ecosystem: 'uv'
    directory: '/api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'uv'
    directory: '/gpu-api'
    schedule:
      interval: 'daily'
