name: finki-hub-chat-bot

networks:
  finki_stack:
    driver: bridge
    name: finki_stack
    # Set external to true to use an existing network
    # external: true

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_KEY: ${API_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GPU_API_URL: ${GPU_API_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      MCP_HTTP_URLS: ${MCP_HTTP_URLS}
      MCP_SSE_URLS: ${MCP_SSE_URLS}
      OLLAMA_URL: ${OLLAMA_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WORKERS: ${WORKERS}
    image: ghcr.io/finki-hub/chat-bot-api:latest
    networks:
      - finki_stack
    ports:
      - "8880:8880"
    restart: unless-stopped

  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER
      timeout: 5s
    image: pgvector/pgvector:pg17
    networks:
      - finki_stack
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  gpu-api:
    environment:
      HF_HOME: /huggingface_cache
      LOG_LEVEL: ${LOG_LEVEL}
      PRELOAD_BGEM3: ${PRELOAD_BGEM3}
    image: ghcr.io/finki-hub/chat-bot-gpu-api:latest
    gpus: all
    networks:
      - finki_stack
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ./hf_cache:/huggingface_cache

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    image: dpage/pgadmin4:latest
    networks:
      - finki_stack
    ports:
      - "5555:80"
    restart: unless-stopped
    volumes:
      - ./pgadmin:/var/lib/pgadmin
